### ISSUE TITLE
升级失败

### ISSUE THREAD

**Issue by Jaffoo** [Fahaxikiii/napcat-1panel#1]
从2.6.25升级到3.0.2失败，且无错误日志

**Comment by Fahaxikiii** [comment]
> 从2.6.25升级到3.0.2失败，且无错误日志

保存数据卸载重新安装吧，有问题，应该是我加了那个packet端口之后，我自己也是卸载重装的，也许是1panel他这个更新机制的问题？加了个变量就不能正常升级。但是他好像会创建新版本容器但是还是提示升级
